### ISSUE TITLE
Memory Leaks Cause Server OOMs (CPU, TF2/ONNX)

### ISSUE THREAD

**Issue by narolski** [triton-inference-server/onnxruntime_backend#102]
**Description**
Using latest Triton `v22.01` with ONNXBackend (self-built) or with the TensorFlow Backend (image from Nvidia Container Registry) and performing the CPU inference there seems to be a memory leak: memory usage increases with each request, finally leading to an OOM for the Triton Inference Server instance.

**Triton Information**
What version of Triton are you using? **v22.01**

Are you using the Triton container or did you build it yourself? **Both the Triton container version and custom ONNX build are affected**.

**To Reproduce**
Steps to reproduce the behavior.

1. Run the Inference server to host the [CRAFT model](https://github.com/namedysx/CRAFT-tensorflow) either in a `model.savedmodel` format (for TensorFlow backend) or `model.onnx` format.
2. Perform multiple inferences using `tritonclient[all]==2.18.0`.
3. Watch the memory usage of Triton Inference Server to increase (locally using `docker stats`).

Model configuration file:
```protobuf
name: "craft"
backend: "onnxruntime"
max_batch_size: 1
input [
  {
    name: "input_2"
    data_type: TYPE_FP32
    dims: [-1, -1, 3]
  }
]
output [
  {
    name: "conv_cls.8"
    data_type: TYPE_FP32
    dims: [-1, -1, 2]
  }
]
instance_group {
  kind: KIND_CPU
  count: 1
}
model_warmup {                                                                        
    name: "CRAFT Warmup"
    batch_size: 1                                                                     
    inputs: {                                                                         
        key: "input_2"                                                                  
        value: {                                                                      
            data_type: TYPE_FP32                                                      
            dims: [1024, 1024, 3]                                                                 
            zero_data: false
        }                                                                             
    }                                                                                 
}  

```

Example tritonclient usage (Python 3.10):
```python
        import tritonclient.grpc as grpcclient
        from tritonclient.grpc import InferenceServerClient, InferenceServerException
  
        client = InferenceServerClient(
            url=TRITON_GRPC_SERVICE,
        )
        TRITON_CRAFT_MODEL_NAME = "craft"
        TRITON_CRAFT_MODEL_VERSION = "1"
        TRITON_CRAFT_MODEL_INPUT_NAME = "input_2"
        TRITON_CRAFT_MODEL_OUTPUT_NAME = "conv_cls.8"

        input = grpcclient.InferInput(
            name=TRITON_CRAFT_MODEL_INPUT_NAME,
            shape=[1, input_image.shape[0], input_image.shape[1], input_image.shape[2]],
            datatype="FP32",
        )
        output = grpcclient.InferRequestedOutput(TRITON_CRAFT_MODEL_OUTPUT_NAME)
        input.set_data_from_numpy(np.array([input_image]))
            
         response = self.client.infer(
                model_name=TRITON_CRAFT_MODEL_NAME, inputs=[input], outputs=[output], 
                client_timeout=TRITON_GRPC_TIMEOUT
            )
        result = response.as_numpy(name=TRITON_CRAFT_MODEL_OUTPUT_NAME)
```

Example output of Triton Inference Server with `--log-verbose=1` flag:

```bash
I0217 15:49:51.941706 1 grpc_server.cc:3206] New request handler for ModelInferHandler, 89
I0217 15:49:51.941713 1 model_repository_manager.cc:590] GetModel() 'craft' version -1
I0217 15:49:51.941723 1 model_repository_manager.cc:590] GetModel() 'craft' version -1
I0217 15:49:51.941744 1 infer_request.cc:566] prepared: [0x0x7f43c401c490] request id: , model: craft, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 1, priority: 0, timeout (us): 0
original inputs:
[0x0x7f43c401c748] input: input_2, type: FP32, original shape: [1,1024,1024,3], batch + shape: [1,1024,1024,3], shape: [1024,1024,3]
override inputs:
inputs:
[0x0x7f43c401c748] input: input_2, type: FP32, original shape: [1,1024,1024,3], batch + shape: [1,1024,1024,3], shape: [1024,1024,3]
original requested outputs:
conv_cls.8
requested outputs:
conv_cls.8

I0217 15:49:51.941788 1 onnxruntime.cc:2427] model craft, instance craft_0, executing 1 requests
I0217 15:49:51.941796 1 onnxruntime.cc:1334] TRITONBACKEND_ModelExecute: Running craft_0 with 1 requests
2022-02-17 15:49:51.941856332 [I:onnxruntime:log, bfc_arena.cc:306 AllocateRawInternal] Extending BFCArena for Cpu. bin_num:20 (requested) num_bytes: 549453824 (actual) rounded_bytes:549453824
2022-02-17 15:49:51.941888464 [I:onnxruntime:log, bfc_arena.cc:186 Extend] Extended allocation by 1073741824 bytes.
2022-02-17 15:49:51.941898397 [I:onnxruntime:log, bfc_arena.cc:189 Extend] Total allocated bytes: 2281701376
2022-02-17 15:49:51.941904942 [I:onnxruntime:log, bfc_arena.cc:192 Extend] Allocated memory at 0x7f435bffe040 to 0x7f439bffe040
2022-02-17 15:49:51.959883920 [I:onnxruntime:, sequential_executor.cc:155 Execute] Begin execution
```

The last part is especially important, since it seems that the ONNX Runtime (in this case) allocates an additional 1 GB+ of memory:

```bash
2022-02-17 15:49:51.941888464 [I:onnxruntime:log, bfc_arena.cc:186 Extend] Extended allocation by 1073741824 bytes.
2022-02-17 15:49:51.941898397 [I:onnxruntime:log, bfc_arena.cc:189 Extend] Total allocated bytes: 2281701376
2022-02-17 15:49:51.941904942 [I:onnxruntime:log, bfc_arena.cc:192 Extend] Allocated memory at 0x7f435bffe040 to 0x7f439bffe040
2022-02-17 15:49:51.959883920 [I:onnxruntime:, sequential_executor.cc:155 Execute] Begin execution
```

OOM happens after the last log.

**Expected behavior**

Nvidia Triton Inference Server should not allow for the OOM. Memory should be freed after the inference request is performed.

How can I fix this issue?

**Comment by tanmayv25** [comment]
@askhade  Can we expose above options in onnxruntime backend? Do you have any other solutions?

**Comment by narolski** [comment]
> There are some examples in the https://github.com/triton-inference-server/server/tree/main/deploy you can check them out.

@Tabrizian thank you! 🙏 

I can also confirm that using the fixed-size inputs for the model helped to achieve stable memory usage in my tests on development and production environments.

Still, the configuration option of memory usage strategy for ONNXRuntime on CPU builds would be beneficial.

Right now, I observe the following:
1. After model warmup (1 request, fixed-size input, batch size 1, fullconfiguration posted [here](https://github.com/triton-inference-server/onnxruntime_backend/issues/102#issue-1149087493)) our Triton instance uses ~600 MB of memory
2. After another request (same size of input, but non-random data) memory usage increases to ~1.2 GB
3. After several more requests, memory usage stabilizes at ~1.5 GB

Thus, I presume that replacing the default `arena_extend_strategy=kNextPowerOfTwo` with a less aggressive one for ONNXRuntime would result in a reduction of memory usage of Triton, which could be really beneficial.

I'll be looking forward to your thoughts on that. Also, thank you for being so helpful and responsive - kudos 🎉

**Comment by narolski** [comment]
@Tabrizian @tanmayv25 @askhade do you happen to have any updates regarding the reported issue or any feedback on the observations I've made? 🙏 

While the fixed-size inputs have stabilized the memory usage of my Triton instance with ONNXRuntime, sadly it increased the average inference time of our CRAFT model - since I've found no other way to fix input size of CNN than to scale up/down images and add padding so that the input image is always a rectangle.

Do you happen to have any other proposals on fixing input size that will not negatively affect the inference time? I must say, that I am a bit bummed out about the current state of my Triton-based project, any help would be appreciated 💯

**Comment by pranavsharma** [comment]
I've not reproduced this yet. I'll try to do that today and report back if my findings differ. As for the configs, we've 3 options:

1. Disable the arena altogether for CPU. This should be easy to expose in Triton via 'parameters'. There're some obvious downsides to disabling the arena, but it really depends on your workload.
2. Expose the arena config options. This can be done in 2 ways.
   - ORT doesn't allow per session arena configs, hence they cannot be exposed in 'parameters'. ORT allows the user to configure and register a CPU allocator with custom arena cfgs, but this allocator is then registered at the env level (with the [option](https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/session/onnxruntime_session_options_config_keys.h#L25) to use/not use the env registered allocator at a per session level). Since the env is created only once in the process lifecycle the arena cfg options will have to be exposed as cmd line arguments like [this](https://github.com/triton-inference-server/onnxruntime_backend#command-line-options) in addition to exposing [this](https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/session/onnxruntime_session_options_config_keys.h#L25) via 'parameters' to allow users to actually use this customized allocator.
   - Another option is for ORT to allow users to configure arena cfgs at the session level after which these can be exposed in Triton via 'parameters'. This requires some work in both ORT and Triton ORT backend.
   
 Option #1 is the fastest and something you can try right now by changing onnxruntime.cc and adding this line of code ```THROW_IF_BACKEND_MODEL_ORT_ERROR(ort_api->DisableCpuMemArena(soptions));``` [here](https://github.com/triton-inference-server/onnxruntime_backend/blob/main/src/onnxruntime.cc#L209).

**Comment by pranavsharma** [comment]
Option #1 is merged to master. This should definitely help. We'll look into seeing how other arena params can be exposed after this.

**Comment by narolski** [comment]
@pranavsharma thank you for tremendous help 🎉 

I will experiment with these parameters and let you know if they help us fix the memory management issues for model inference on CPUs.

**Comment by narolski** [comment]
@pranavsharma I can now confirm that setting the `enable_mem_area` and `enable_mem_pattern` flags to `0` based on changes introduced in https://github.com/triton-inference-server/onnxruntime_backend/pull/106 has successfully resolved our memory management issues, as confirmed by my internal tests on various pre-prod and prod environments.

This chart shows the memory usage before and after the addition of flags you've introduced to the model's configuration:

<img width="1312" alt="Zrzut ekranu 2022-04-22 o 08 18 01" src="https://user-images.githubusercontent.com/13568442/164615009-58d1c17a-d9d0-43e3-80f2-be419c57c6f3.png">
 
I'm anxious to see whether `onnxruntime==1.11.0` will introduce any further memory management-related improvements. However, it seems that the issue can be resolved when latest `onnxruntime-backend` is released with the config options exposed (I've prepared my own build for tests).

Thank you so much for your help! 💯 You guys are amazing!

**Comment by pranavsharma** [comment]
ORT 1.11 does have some memory management related improvements. See here https://github.com/microsoft/onnxruntime/releases/tag/v1.11.0.

**Comment by narolski** [comment]
@pranavsharma Thank you! Is it safe to use `ORT 1.11` with `onnxbackend r22.04`, or should I wait for a newer release of the latter? The compatibility matrix states that I should use `ORT 1.10`.

**Comment by pranavsharma** [comment]
There are some issues with r22.04 and ORT 1.11 combination. I would wait for a latter release of Triton. I [fixed a bug](https://github.com/triton-inference-server/onnxruntime_backend/pull/117) yesterday that was preventing ORT 1.11 upgrade in Triton.

**Comment by narolski** [comment]
@pranavsharma I've tested thoroughly `ORT 1.10` with `tritonserver 22.03` and `triton-onnxbackend 22.04` and, by using the new memory flags, I have successfully resolved a memory leak.

I've now upgraded by image to `tritonserver 22.06`, `triton-onnxbackend 22.06` and `onnxruntime 1.11` and I do not see any regression.
