### ISSUE TITLE
Expose ONNXRuntime memory arena shrinkage option as configurable parameter.

### ISSUE THREAD

**Issue by zeruniverse** [triton-inference-server/onnxruntime_backend#103]
**Is your feature request related to a problem? Please describe.**
Due to ONNXRuntime memory arena, if a model is inferenced with a large batch size, the model will take huge amount of GRAM forever, which prevents other models from running.

**Describe the solution you'd like**
ONNXRuntime has a run config option "memory.enable_memory_arena_shrinkage" to address this issue. With it enabled, memory arena can be shrinked after each run, with some compromise on performance. This option should be exposed as a configurable parameter.

I have implemented my own version as follows in `onnxruntime.cc` and it solved my problem. I think many other people would like the same feature. However, I hard-coded `cpu:0` and `cpu:0;gpu:0` because my production env only has one GPU, so I didn't make it a pull request.

```
int shrink_arena = 0;
  triton::common::TritonJson::Value params;
  if (model_state->ModelConfig().Find("parameters", &params)) {
    THROW_IF_BACKEND_MODEL_ERROR(TryParseModelStringParameter(
        params, "enable_arena_shrinkage", &shrink_arena, 0));
  }

  if(shrink_arena){
#ifdef TRITON_ENABLE_GPU
    THROW_IF_BACKEND_INSTANCE_ORT_ERROR(ort_api->AddRunConfigEntry(runOptions_, "memory.enable_memory_arena_shrinkage", "cpu:0;gpu:0"));
#else
    THROW_IF_BACKEND_INSTANCE_ORT_ERROR(ort_api->AddRunConfigEntry(runOptions_, "memory.enable_memory_arena_shrinkage", "cpu:0"));
#endif
  }
```

**Comment by pranavsharma** [comment]
Resolved.

**Comment by zeruniverse** [comment]
@pranavsharma Thanks for implementing this but can arena shrink be smarter? Currently, user should specify where the model is (e.g. cpu:0), but actually triton knows where the model is better than user. I suggest user just specify this value as 0 or 1, and triton translates it to cpu:0, gpu:0, gpu:1 etc.

**Comment by pranavsharma** [comment]
@zeruniverse We would like to mirror the configs from the ORT framework here as much as possible. This has a few advantages.
1. It allows us to point to existing documentation that is being continually enriched.
2. Users can search for the config in https://github.com/Microsoft/onnxruntime/issues or get perf recommendations and when a config is mentioned they won't have to do think how to translate the ORT framework string to ORT backend config.
3. It avoids the unnecessary translation of configs from ORT backend to ORT framework invocations.
When you configure Triton to run with ORT backend and CPU, you've to mention the instance kind to be CPU any way. I realize you've to repeat it in this string but the minor inconvenience is tradeoff against the advantages listed above.

**Comment by zeruniverse** [comment]
@pranavsharma thanks for your reply! Yes, I understand for CPU, user can just specify cpu:0. The problem is when there’re multiple GPUs(say 2) and each GPU has one instance of model X. In this case, instance 1 should have value gpu:0 and instance 2 should have gpu:1. I don’t know if user would be able to configure this since I assume parameter settings apply to all instances
