### ISSUE TITLE
More options to control TensorRT execution provider.

### ISSUE THREAD

**Issue by DavidLangworthy** [triton-inference-server/onnxruntime_backend#20]
Need to come up with config proto spec.  

https://github.com/microsoft/onnxruntime/blob/master/docs/execution_providers/TensorRT-ExecutionProvider.md

**Comment by ppyun** [comment]
Triton-ONNXRT model’s config needs to be able to enable FP16 inferencing (like Triton-TensorFlow) as a 1st priority so that there is no server downtime without restarting with docker run -e ORT_TENSORRT_FP16_ENABLE=1

**Comment by stevenlix** [comment]
After discussion with @ppyun , we will address this issue by removing env variables and passing TRT configurations to ORT session.
