### ISSUE TITLE
How can I control the cuda memory for onnx models?

### ISSUE THREAD

**Issue by LLsmile** [triton-inference-server/onnxruntime_backend#56]
How can I control the cuda memory for onnx models? Is there any parameters, such as gpu-memory-fraction in tensorflow, which control the cuda memory allocated for models?

**Comment by tanmayv25** [comment]
@askhade Do you have any guidance for the user?

**Comment by askhade** [comment]
https://github.com/triton-inference-server/onnxruntime_backend/pull/72 enables configuring gpu mem limit for CUDA provider.
