### ISSUE TITLE
Re-use generated TensorRT plan when instance groups or multi-gpu

### ISSUE THREAD

**Issue by damonmaria** [triton-inference-server/onnxruntime_backend#66]
**Is your feature request related to a problem? Please describe.**
When using TensorRT accelerator for an ONNX model, if the model is duplicated either through instance groups, or across GPUs then the ONNX -> TensorRT conversion process is repeated each time. This takes 4 minutes to per conversion for my model so quickly becomes excessive.  

**Describe the solution you'd like**
When using instance groups then the TensorRT model is only generated once, and the resulting TensorRT plan is duplicated for the other instances.

I understand this may be a little harder to do across GPUs, but as long as they have identical specs it should be possible. 

**Describe alternatives you've considered**
1. Just waiting (which for me is then about 16 minutes for Triton to start). 
2. Converting the model to TensorRT myself beforehand, but we deploy this setup to different models of GPU so this can't be a build step for us.

**Comment by askhade** [comment]
@sunhailin-Leo and  
damonmaria : We recently enabled trt engine cache for ort backend. This will be available starting triton 21.09 version. You can build from source as well if you want to test right away.

Note: The cache is not enabled by default, you need to explicitly enable it in the model config as follows: https://github.com/triton-inference-server/onnxruntime_backend/blob/main/README.md#onnx-runtime-with-tensorrt-optimization

**Comment by sunhailin-Leo** [comment]
@askhade
* Actually, I used tenorrt plan as the trition backend. So, how can I use the cache? 
* Ps: My model is fine-tune by tensorflow, after fine-tune we convert it to tensorrt model then deploy on triton.

**Comment by deadeyegoodwin** [comment]
@sunhailin-Leo  this discussion is about the ONNX-TRT integration, not about TensorRT models running on TensorRT backend. For cases using tensorrt models there should not be any slowness in loading the models. If you have an issue specific to tensorrt models please file a new issue in the server/ repo.

**Comment by askhade** [comment]
Closing this issue since trt engine caching for ort backend is enabled in 21.09 @damonmaria Please give it a try and if you run into any issues please reopen this issue or create a new one.
