### ISSUE TITLE
Why is it slower to use openvino than not ？

### ISSUE THREAD

**Issue by aixuedegege** [triton-inference-server/onnxruntime_backend#84]
Why is it slower to use the following configuration than not ？

optimization { execution_accelerators {
  cpu_execution_accelerator : [ {
    name : "openvino"
  }]
}}

**Comment by askhade** [comment]
@aixuedegege - Whether this accelerator will bring in perf gains or not depends on multiple factors, the specific model you’re trying to run, the session and run options you’ve selected, and of course, your specific hardware target.

**Comment by aixuedegege** [comment]
ok tks a lot
