### ISSUE TITLE
how to make the onnx to support batch

### ISSUE THREAD

**Issue by zijin520** [triton-inference-server/onnxruntime_backend#88]
**Description**
how to configure to make the onnx model can use batching?

**Triton Information**
E1207 07:13:40.323463 1639 model_repository_manager.cc:1890] Poll failed for model directory 'cat_dog_onnx_batch': model input has different size for dims and reshape for cat_dog_onnx_batch
 

Are you using the Triton container or did you build it yourself?
the container

**To Reproduce**
My onnx model is transformed from a caffe model with input as bellow.
input_param{
    shape: {dim: 2 dim: 3 dim: 32 dim: 32}
  }

My config.pbtxt:
name: "cat_dog_onnx_batch"
platform: "onnxruntime_onnx"
max_batch_size : 2
input [
  {
    name: "data_input"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 32, 32 ]
    reshape { shape: [ 2, 3, 32, 32 ] }
  }
]
output [
  {
    name: "prob_Y"
    data_type: TYPE_FP32
    dims: [ 2 ]
    reshape { shape: [ 2, 2 ] }
    label_filename: "cat_dog_labels.txt"
  }
]

instance_group [
  {
    count: 2
    kind: KIND_CPU
  }]
dynamic_batching {
  }

**Expected behavior**
dynamic_batching can be used in a model.onnx

**Comment by CoderHam** [comment]
@zijin520 are you asking how to use dynamic batching in Triton with an onnx model that already supports batching? 

You will need to create max_batch_size to the preferred batch size you wish to run for when using dynamic batching.

**Comment by zijin520** [comment]
@CoderHam Hi CoderHam, thanks for your attention. I know how to user the  dynamic batching in other backends. But I got error message when I was using onnx. And I cannot find the reason. Could you help to give some advice for it. Or there may be some onnx examples showing the configuration of dynamic batching? Thanks.
