### ISSUE TITLE
Model hangs when warming up for tensorrt optimization

### ISSUE THREAD

**Issue by chajath** [triton-inference-server/onnxruntime_backend#97]
**Description**
ONNX with tensorrt optimization hangs/times out when launched with warmup.

**Triton Information**
What version of Triton are you using? `r21.12`

Are you using the Triton container or did you build it yourself? Using Triton container `nvcr.io/nvidia/tritonserver:21.12-py3`

**To Reproduce**
We have an image embedding network that we compiled from CLIP with ViT-b32 model.

We have a model config:

```
name: "clip_embedding_gpu"
platform: "onnxruntime_onnx"
max_batch_size: 128
input [{
  name: "IMAGE_PREPROCESSED"
  data_type: TYPE_FP32
  dims: [3, 224, 224]
}]
output [{
  name: "IMAGE_EMBEDDING"
  data_type: TYPE_FP16
  dims: [512]
}]

instance_group {
  kind: KIND_GPU
}
dynamic_batching {
  max_queue_delay_microseconds: 25
}
optimization {
  execution_accelerators {
    gpu_execution_accelerator: [
      {
        name: "tensorrt"
        parameters [
          {
            key: "precision_mode"
            value: "FP16"
          }
        ]
      }
    ]
  }
}
```

When starting up, we noticed that models were timing out for about 6~7 runs of `perf_analyzer` then it starts to produce results. We saw about 25% speedup.

Now, when we enable warm up:

```
model_warmup [{
  name: "warmup"
  batch_size: 128
  inputs: [{
    key: "IMAGE_PREPROCESSED"
    value: {
      data_type: TYPE_FP32
      dims: [3, 224, 224]
      zero_data: true
    }
  }]
}]
```

We saw a little delay in triton server startup, which is expected. However, perf_analyzer run now times out without every recovering.

**Expected behavior**
Once tritonserver started, perf_analyzer should show performance at an optimal level.

**Comment by askhade** [comment]
@chajath : Can you share your model so that we can try and repro this issue on our end? If you cannot share the exact model, a similar network with randomized weights also works provided it reproduces the issue.

**Comment by chajath** [comment]
Actually, it was just that model warmup was taking very very long, I think. In the new release I've managed to warm the model up. Closing this issue.
